//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordersNTransfers.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ordersNTransfers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oms15v2.
        /// </summary>
        internal static string dbname {
            get {
                return ResourceManager.GetString("dbname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DSN=HANA; SERVERNODE=192.168.11.20:30015; UID=SYSTEM; PWD=Aez1NtM6.
        /// </summary>
        internal static string HCS {
            get {
                return ResourceManager.GetString("HCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 192.168.11.44:8069.
        /// </summary>
        internal static string hostname {
            get {
                return ResourceManager.GetString("hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        internal static string id_interfaz {
            get {
                return ResourceManager.GetString("id_interfaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XTEZDRV73Z4SJWAUASQFGIRAH45LYA5N.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grs_oms.
        /// </summary>
        internal static string MSdbP {
            get {
                return ResourceManager.GetString("MSdbP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grs_oms.
        /// </summary>
        internal static string MSdbT {
            get {
                return ResourceManager.GetString("MSdbT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2303.
        /// </summary>
        internal static string MSprt {
            get {
                return ResourceManager.GetString("MSprt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MA_Ivo19MYsGRS.
        /// </summary>
        internal static string MSpwd {
            get {
                return ResourceManager.GetString("MSpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 192.168.11.36.
        /// </summary>
        internal static string MSsrv {
            get {
                return ResourceManager.GetString("MSsrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserWkspace.
        /// </summary>
        internal static string MSui {
            get {
                return ResourceManager.GetString("MSui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string shipping_status_arrived {
            get {
                return ResourceManager.GetString("shipping_status_arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30013.
        /// </summary>
        internal static string SHPRT {
            get {
                return ResourceManager.GetString("SHPRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NDB@192.168.11.20.
        /// </summary>
        internal static string SHSVR {
            get {
                return ResourceManager.GetString("SHSVR", resourceCulture);
            }
        }
    }
}
